### ISSUE TITLE
Line endings at end of dumps() not consistent

### ISSUE THREAD

**Issue by palazzol** [christoph2/objutils#13]
Very minor nitpick on a _great_ library

For the ihex format, the last line gets a final end of line character, while for srec there is no final line ending.

It looks like maybe all of the writers that use compose_footer() do not return a final line ending, but ihex's compose_footer() does.

I'm not sure what the convention should be? I like final line endings :)

**Comment by christoph2** [comment]
> I like final line endings :)

Yes, Absolutly 😃
