### ISSUE TITLE
Error when using the "bin" codec

### ISSUE THREAD

**Issue by thombet** [christoph2/objutils#9]
Hello,

I am using objutils 0.4.2 (by the way I saw that the code is labelled 0.4.5 but only 0.4.2 was released in PyPI: is it normal?) and I am not able to use the `bin` codec.

When I use this code:
```python
from objutils import dump
from objutils.elf import ElfParser

ep = ElfParser("file.elf")
img = ep.create_image()
if img:
    dump("bin", "converted-file.bin", img)
```

I get the following error:

```
Traceback (most recent call last):
  File "script.py", line 11, in <module>
    dump(output_format, output_file_path, img)
  File "<path>\venv\lib\site-packages\objutils\__init__.py", line 162, in dump
    registry.get(codec_name).Writer().dump(*args, **kws)
  File "<path>\venv\lib\site-packages\objutils\binfile.py", line 68, in dump
    fp.write(self.dumps(image, filler))
AttributeError: 'str' object has no attribute 'write'
```

I was able to work around this issue by hacking the code in [the dump() method of the Writer class in binfile.py](https://github.com/christoph2/objutils/blob/650c41eeb27a03c92ae8dff4465c8d5592df893d/objutils/binfile.py#L67) with:
```python
def dump(self, fp, image, filler = b'\xff', **kws):
    if isinstance(fp, str):
        fp = open(fp, "wb")
    fp.write(self.dumps(image, filler))
    if hasattr(fp, "close"):
        fp.close()
```

Is this error expected? If not, could you please fix the issue? :)

Thanks in advance.

**Comment by christoph2** [comment]
Good morning Thomas, 

No, this behavior isn't expected  -- I've fixed it and I hope it works.
Normally, PyPI upload should happen automatically, I'll check it.

**Comment by thombet** [comment]
Great, thanks!

Totally unrelated question: I would like to use your library to replace [objcopy](https://man7.org/linux/man-pages/man1/objcopy.1.html).
Could you please suggest objutils code which would be equivalent to the options `--strip-dwo`  and `--strip-debug` of objcopy?

**Comment by thombet** [comment]
Ok so I will have a look to the existing scripts and I will build my own to achieve my goal.

To conclude this issue, I would like to get a version of objutils with a working "bin" codec from PyPI, not from GitHub.
Do you plan to make a new release with the fix you implemented?

**Comment by christoph2** [comment]
OK, automatic PyPI upload seems to work again.

**Comment by thombet** [comment]
The version 0.4.7 which is now available in PyPI fixes the initial issue, thanks!
